language: python
python: 2.7
before_install:
  - sudo apt-get install libsnappy-dev

install:
  - git clone --depth=1 https://github.com/scudette/rekall-test.git
  - python setup.py install

script:
  - python tools/testing/test_suite.py -c rekall-test/tigger/tests.config --inline
